
const IDENTIFIER = "player";

export const FETCH_PLAYLIST_SUCCESS = `${IDENTIFIER}FETCH_SONG_SUCCESS`;
export const FETCH_PLAYLIST_FAILURE = `${IDENTIFIER}FETCH_SONG_FAILURE`;
export const FETCH_PLAYLIST_REQUEST = `${IDENTIFIER}FETCH_SONG_REQUEST`;