const IDENTIFIER = "player";
export const FETCH_PLAYLIST_SUCCESS = `${IDENTIFIER}FETCH_SONG_SUCCESS`;
export const FETCH_PLAYLIST_FAILURE = `${IDENTIFIER}FETCH_SONG_FAILURE`;
export const FETCH_PLAYLIST_REQUEST = `${IDENTIFIER}FETCH_SONG_REQUEST`;

export const LOGIN_SUCCESS = `${IDENTIFIER}LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `${IDENTIFIER}LOGIN_FAILURE`;
export const LOGIN_REQUEST = `${IDENTIFIER}LOGIN_REQUEST`;


export const PREV = `${IDENTIFIER}PREV`;
export const PLAY = `${IDENTIFIER}PLAY`;
export const PAUSE = `${IDENTIFIER}PAUSE`;
export const NEXT = `${IDENTIFIER}NEXT`;
export const SELECT_TRACK = `${IDENTIFIER}SELECT_TRACK`;
export const RANDOMIZE_PLAYLIST = `${IDENTIFIER}RANDOMIZE_PLAYLIST`;
export  const PROGRESS = `${IDENTIFIER}PROGRESS`;


export const ADD_TRACK = `${IDENTIFIER}ADD_TRACK`;
export const REMOVE_TRACK = `${IDENTIFIER}REMOVE_TRACK`;

export const FETCH_SEARCH_VALUE = `${IDENTIFIER}FETCH_SEARCH_VALUE`;