const IDENTIFIER = "player";

export const FETCH_PLAYLIST_SUCCESS = `${IDENTIFIER}FETCH_SONG_SUCCESS`;
export const FETCH_PLAYLIST_FAILURE = `${IDENTIFIER}FETCH_SONG_FAILURE`;
export const FETCH_PLAYLIST_REQUEST = `${IDENTIFIER}FETCH_SONG_REQUEST`;
export const FETCH_MOCK_PLAYLIST = `${IDENTIFIER}FETCH_MOCK_PLAYLIST`;
export const FOO = `${IDENTIFIER}FOO`;

export const PREV = `${IDENTIFIER}PREV`;
export const PLAY = `${IDENTIFIER}PLAY`;
export const PAUSE = `${IDENTIFIER}PAUSE`;
export const NEXT = `${IDENTIFIER}NEXT`;
export const SELECT_TRACK = `${IDENTIFIER}SELECT_TRACK`;
export const PROGRESS = `${IDENTIFIER}PROGRESS`;

export const FETCH_SEARCH_VALUE = `${IDENTIFIER}FETCH_SEARCH_VALUE`;